package me.nathanfallet.suitebde.models.roles

enum class Permission {

    ADMIN,
    DOMAINS_CREATE,
    DOMAINS_UPDATE,
    DOMAINS_DELETE,
    ASSOCIATIONS_SUBSCRIPTIONS_CREATE,
    ASSOCIATIONS_SUBSCRIPTIONS_UPDATE,
    ASSOCIATIONS_SUBSCRIPTIONS_DELETE,
    USERS_VIEW,
    USERS_UPDATE,
    ROLES_VIEW,
    ROLES_CREATE,
    ROLES_UPDATE,
    ROLES_DELETE,
    ROLES_USERS,
    WEBPAGES_VIEW,
    WEBPAGES_CREATE,
    WEBPAGES_UPDATE,
    WEBPAGES_DELETE,
    WEBMENUS_VIEW,
    WEBMENUS_CREATE,
    WEBMENUS_UPDATE,
    WEBMENUS_DELETE,
    EVENTS_VIEW,
    EVENTS_CREATE,
    EVENTS_UPDATE,
    EVENTS_DELETE,
    CLUBS_VIEW,
    CLUBS_CREATE,
    CLUBS_UPDATE,
    CLUBS_DELETE,
    CLUBS_USERS,
    ;

    infix fun inAssociation(associationId: String) =
        PermissionInAssociation(this, associationId)

}
