{{ if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "suitebde.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "suitebde.labels" . | indent 4 }}
  {{- with .Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  mysql-username: {{ .Values.mysql.auth.username | default "root" | b64enc | quote }}
  {{ if not .Values.mysql.auth.existingSecret }}
  mysql-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  {{ end }}
  jwt-secret: {{ .Values.jwt.secret | b64enc | quote }}
  email-password: {{ .Values.email.password | b64enc | quote }}
  cloudflare-account: {{ .Values.cloudflare.account | b64enc | quote }}
  cloudflare-token: {{ .Values.cloudflare.token | b64enc | quote }}
{{ end }}
